### ISSUE TITLE
creating sleeping-dragon landing site

### ISSUE THREAD

**Issue by 1Snake001** [molitio/molitio-core#109]
> @1Snake001, @bobesomogyi  this is a new format that i am trying to help the development process. the goal is to have a proper summary of what needs to be done, do only what needs to be done, and track what has been done. let me know your feedback about this experimental process.

 
So here is the Story:

As a developer, i experience ui issue with the "glowing" animation in the molitio storybook/sleeping-dragon app. The recent major overhaul caused the issue highly likely.  the [the icon group](https://github.com/molitio/molitio-core/blob/9e5b56f715c8a5fa27c2bfd7b180939be61659d1/packages/ui-core/src/ui-common/styles/StyledIconGroup.ts#L36) is here. the state change related refactor split the css logic to couple of different states. each state can be distinguished by `isActive` or `glowing | drop-shadow` logical operators. study the codebase, learn the connecting components only related to this issue for now. 

the ui bug:
<img width="447" alt="Screenshot 2022-11-30 at 16 33 32" src="https://user-images.githubusercontent.com/8149214/204937556-6b27fca0-6ad5-4a9a-b0c1-27905b8c9c7d.png">

expected by design
<img width="407" alt="Screenshot 2022-11-30 at 16 52 28" src="https://user-images.githubusercontent.com/8149214/204939566-780a2a48-52b4-4644-80e4-16443b26290a.png">

at this [line](https://github.com/molitio/molitio-core/blob/9e5b56f715c8a5fa27c2bfd7b180939be61659d1/packages/ui-storybook/src/app-stories/SleepingDragon.stories.tsx#L46) where you can configure a few settings for the hero page and the hero icons.  `iconBorderRadius, heroIconType, etc` 

you can also use [this](https://github.com/molitio/molitio-core/blob/6f82ec8e422e5357d52158ee22b89f92344209c6/packages/ui-storybook/src/ui-common-stories/CommonComponent.stories.tsx#L22) molitio storybook/components/common story made for the development of the icon group with different themes activated on them, which can be also configured

this story track the progress on the issue, and in general this issue/branch tracks the work on the components preparing for the next release, changes will need to be made in both ui-core and sleeping-dragon projects. we go step by step for issues, and keep track of the progress. 

for now the only objective is the icon border "glowing" effect, and we proceed once it is completed, and we can use this branch to track it

the final aim is to prepare it for the release. for that i link @bobesomogyi as well to consult regarding design questions

contact or comment if you have any questions please

🧭 `git fetch origin
 git checkout 109-creating-sleeping-dragon-landing-site`

objective
- [ ] molitio hero icon group should display properly according to the most [recent design](https://www.figma.com/file/TXJCIgDCJ7mbs7utbkqKMH/molitio_soon?node-id=0%3A1&t=yvwHKY53OrMqemwg-1)

**Comment by peterkollerlv** [comment]
updated issue header

**Comment by bobesomogyi** [comment]
> > @1Snake001, @bobesomogyi  this is a new format that i am trying to help the development process. the goal is to have a proper summary of what needs to be done, do only what needs to be done, and track what has been done. let me know your feedback about this experimental process.
> 
> So here is the Story:
> 
> As a developer, i experience ui issue with the "glowing" animation in the molitio storybook/sleeping-dragon app. The recent major overhaul caused the issue highly likely. the [the icon group](https://github.com/molitio/molitio-core/blob/9e5b56f715c8a5fa27c2bfd7b180939be61659d1/packages/ui-core/src/ui-common/styles/StyledIconGroup.ts#L36) is here. the state change related refactor split the css logic to couple of different states. each state can be distinguished by `isActive` or `glowing | drop-shadow` logical operators. study the codebase, learn the connecting components only related to this issue for now.
> 
> the ui bug: <img alt="Screenshot 2022-11-30 at 16 33 32" width="447" src="https://user-images.githubusercontent.com/8149214/204937556-6b27fca0-6ad5-4a9a-b0c1-27905b8c9c7d.png">
> 
> expected by design <img alt="Screenshot 2022-11-30 at 16 52 28" width="407" src="https://user-images.githubusercontent.com/8149214/204939566-780a2a48-52b4-4644-80e4-16443b26290a.png">
> 
> at this [line](https://github.com/molitio/molitio-core/blob/9e5b56f715c8a5fa27c2bfd7b180939be61659d1/packages/ui-storybook/src/app-stories/SleepingDragon.stories.tsx#L46) where you can configure a few settings for the hero page and the hero icons. `iconBorderRadius, heroIconType, etc`
> 
> this story track the progress on the issue, and in general this issue/branch tracks the work on the components preparing for the next release, changes will need to be made in both ui-core and sleeping-dragon projects. we go step by step for issues, and keep track of the progress.
> 
> for now the only objective is the icon border "glowing" effect, and we proceed once it is completed, and we can use this branch to track it
> 
> the final aim is to prepare it for the release. for that i link @bobesomogyi as well to consult regarding design questions
> 
> contact or comment if you have any questions please
> 
> 🧭 `git fetch origin git checkout 109-creating-sleeping-dragon-landing-site`
> 
> objective
> 
> * [ ]  molitio hero icon group should display properly according to the most recent design. { @bobesomogyi can we update figma design link here please? if you cant edit this, than send it to me }

You can find the Figma link below: 

https://www.figma.com/file/TXJCIgDCJ7mbs7utbkqKMH/molitio_soon?node-id=0%3A1&t=yvwHKY53OrMqemwg-1

**Comment by peterkollerlv** [comment]
updated figma link, thx @bobesomogyi. and @1Snake001 i added a link for the storybook components made for the hero icon group development, it has the icons with both themes, and it can be configure. the background color can be changed... i just needed contrast. 🥽 
<img width="321" alt="Screenshot 2022-11-27 at 19 08 02" src="https://user-images.githubusercontent.com/8149214/204975198-d603c9f7-ed97-4adf-9931-d755f0bd0c70.png">
