### ISSUE TITLE
documentation update with a tree of components organized in their categories

### ISSUE THREAD

**Issue by vycos-zen** [molitio/molitio-core#98]
# extend ui-core/readme with the major component categories and an extensive tree of existing components and the ones needed for project Art Natalia in a markdown format, with table of contents generated

collaboratively design a logical component breakdown like (list, list-header, list-item, item-card) for all of our components 

**guide for **M**ark **D**own format:**

- [**MD** guide](https://www.markdownguide.org/cheat-sheet/)

**the readme file location:**

- [README.md](https://github.com/molitio/molitio-core/blob/main/packages/ui-core/README.md)

**tool to generate a table of contents:**

- [MD generator](https://ecotrust-canada.github.io/markdown-toc/)

**specs:**

- categories are logically containing components, and their sub components
- only the publicly exported named components should be on the list
- continuously collaborate among the team for feedback and guidance
- if a component reused anywhere, do not nest it as a child
- nest a component under its parent only if it is only used in the particular component

**example:**

## ResourceGallery
- GalleryDisplay
- CategoryBrowser
  - CategoryCard
- ResourceCard

**Comment by peterkollerlv** [comment]
added type doc, it generates documentation properly
